lavc/vaapi_decode: set initial pool size according to dpb_size
intel-media-ci/ffmpeg pull request #121
Opened 2019-11-05 09:10 UTC by fulinjie

Set initial_pool_size dynamically according to dpb_size.

Compared to a fixed pool size for H.264 and HEVC, the usage of
GPU memory could be improved.

Signed-off-by: Linjie Fu <linjie.fu@intel.com>

2019-11-05 09:59 UTC, xuguangxin requested changes

2019-11-05 09:59 UTC, xuguangxin commented on libavcodec/vaapi_decode.c
>  int ff_vaapi_common_frame_params(AVCodecContext *avctx,
How about add new function, ff_vaapi_common_frame_params_with_pdb_size. then ff_vaapi_common_frame_params will call ff_vaapi_common_frame_params_with_pdb_size with size dpb_size = 2.
In this way. you do not need change any code in mpeg2, vc1.... etc.

2019-11-05 09:59 UTC, xuguangxin commented on libavcodec/vaapi_decode.c
> +                                   &ctx->va_config, avctx->hw_frames_ctx,
this changed the original behavious.  It will give 16 to mpeg2. but the previous code only gives 2.

2019-11-06 04:46 UTC, xuguangxin approved these changes
great! thanks Lingjie.

2019-11-11 09:45 UTC, fulinjie commented
All check passed, closed.

2019-11-11 09:45 UTC, closed without merging