libavcodec/vaapi_encode_vp9.c:set a defualt value for log2_tile_columns
intel-media-ci/ffmpeg pull request #377
Opened 2021-03-29 06:57 UTC by zhangyuankun-star

Maximum width of a tile in units of superblocks is 64,
So the number of tile columns is related to the width of the picture.
We should set a defualt value for log2_tile_columns
to to avoid errors in video coding with width over 4096.

Signed-off-by: Zhang yuankun <yuankunx.zhang@intel.com>

2021-03-30 01:34 UTC, zhangyuankun-star commented
@xhaihao @xuguangxin , Can you review this for me ?

2021-03-30 02:24 UTC, xuguangxin requested changes
Did you checked tile width < MIN_TILE_WIDTH_B64(4) super block?

2021-03-30 02:24 UTC, xuguangxin commented on libavcodec/vaapi_encode_vp9.c
> +    numTileColumns = (vpic->frame_width_src + VP9_MAX_TILE_WIDTH - 1) / VP9_MAX_TILE_WIDTH;
please change to num_tile_columns.

2021-03-30 02:24 UTC, xuguangxin commented on libavcodec/vaapi_encode_vp9.c
> +    // Maximum width of a tile in units of superblocks is 64
change 64 to MAX_TILE_WIDTH_B64(64)

2021-03-31 12:53 UTC, xuguangxin requested changes
Please refer to other ffmpeg commit log and change commit message too.

2021-03-31 12:53 UTC, xuguangxin commented on libavcodec/vaapi_encode_vp9.c
> +    vpic->log2_tile_columns = av_log2(num_tile_columns);
this may not right. if you have a 9k video,  num_tile_columns will be 3. vpic->log2_tile_columns will be 1.   each tile columns will large than 4k

2021-04-07 01:39 UTC, xuguangxin requested changes
How about this:
```
avcodec/vaapi_encode_vp9: fix > 4k encode fail issue

This patch will fix following command:
xxxxx

Max width of a vp9 tile is 4096.  If we the source frame > 4096, we need split to multiple tiles.
```
also did you checked MAX_TILE_AREA? what's happened if you encode a 9k x 4096 video?

2021-04-08 04:39 UTC, xuguangxin commented
Max width of a vp9 tile is 4096.  If ~~we~~ the source frame > 4096, we need split to multiple tiles.
Sorry, we need remove the we.

could we use a simplified pipeline like
ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -i input.264 -vf 'scale_vaapi=w=7680:h=4096' -c:v vp9_vaapi output.ivf

2021-04-09 03:00 UTC, xuguangxin approved these changes

2021-04-12 03:25 UTC, zhangyuankun-star commented
I have send this patch to ffmpeg community, so I close this PR.
link:https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210412014724.18563-1-yuankunx.zhang@intel.com/

2021-04-12 03:25 UTC, closed without merging