[WIP] Add vaapi stack
intel-media-ci/ffmpeg pull request #592
Opened 2022-10-25 09:15 UTC by xhaihao

2022-11-11 04:22 UTC, djie1 requested changes

2022-11-11 04:22 UTC, djie1 commented on doc/filters.texi
> +@section hstac_vaapki
hstack_vaapi

2022-11-11 04:45 UTC, xhaihao commented on doc/filters.texi
> +@section hstac_vaapki
Thanks for catching this typo, I'll update it in the new version.

2023-01-19 15:23 UTC, xhaihao commented
see  https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230119083006.3697233-1-haihao.xiang@intel.com/

2023-01-19 15:23 UTC, closed without merging