lavfi/{denoise,procamp,scale,sharpness}_vaapi: add passthrough mode
intel-media-ci/ffmpeg pull request #655
Opened 2023-05-24 08:20 UTC by feiwan1

2023-05-24 14:48 UTC, uartie commented
This change introduces test failures in VPP contrast and saturation when value set at 0.5 and causes a passthrough result.

2023-05-24 14:53 UTC, uartie commented
> This change introduces test failures in VPP contrast and saturation when value set at 0.5 and causes a passthrough result.

```
$ ffmpeg ... 'format=nv12|vaapi,hwupload,procamp_vaapi=s=0.5,hwdownload,format=nv12' ...
<snip>
[procamp_vaapi @ 0x55d66f19d100] Using VAAPI filter passthrough mode.
<snip>
psnr:expect = [100.0, 37.5973, 43.2666, 100.0, 40.1115, 44.8443]
psnr:actual = [100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
```

2023-05-24 15:17 UTC, uartie requested changes

2023-05-24 15:17 UTC, uartie commented on libavfilter/vf_procamp_vaapi.c
> +        vpp_ctx->passthrough = 1;
Use `fabs` to fix test regressions

2023-05-25 01:57 UTC, feiwan1 commented on libavfilter/vf_procamp_vaapi.c
> +        vpp_ctx->passthrough = 1;
Fixed. Thanks.

2023-05-25 15:00 UTC, uartie commented
LGTM

2023-05-25 15:03 UTC, uartie commented
Maybe change `{denoise,procamp,scale,sharpness}_vaapi` to `vaapi_vpp` in commit message title.

2023-05-26 02:49 UTC, feiwan1 commented
> Maybe change `{denoise,procamp,scale,sharpness}_vaapi` to `vaapi_vpp` in commit message title.

vaapi_vpp gives more tendency to summary the changes in base class of vaapi_vpp.c, and better to seperate and commit other vaapi filter changes into single ones like:
1. vaapi_vpp: base function change.
2. scale_vaapi: passthrough mode.
3. ...

So I perfer using current way with {} to stress changes to the vaapi filters. And the style is widely used in ffmpeg like:

commit c889248647780753ec8b05138c7de4a707adb106
Refs: n5.2-dev-1333-gc889248647
Author:     Jan Ekström <jeebjp@gmail.com>
AuthorDate: Wed Oct 19 11:44:03 2022 +0200
Commit:     Thilo Borgmann <thilo.borgmann@mail.de>
CommitDate: Wed Oct 19 11:53:52 2022 +0200

    ffmpeg: Add display_{rotation, hflip, vflip} options

2023-05-30 00:50 UTC, feiwan1 commented
patch submitted to  https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=9025. Close.

2023-05-30 00:50 UTC, closed without merging