Adding large_scle_tile bit
intel-media-ci/ffmpeg pull request #656
Opened 2023-05-25 08:46 UTC by tengjinchung

2023-05-26 01:08 UTC, xhaihao commented on libavcodec/vaapi_av1.c
> +            .large_scale_tile             = frame_header->large_scale_tile,
Please add a check for va-api version at compile time. large_scale_tile is not available in old versions of libva.

2023-05-26 01:10 UTC, xhaihao commented on libavcodec/vaapi_av1.c
> +            .large_scale_tile             = frame_header->large_scale_tile,
Please ignore the above comment.

2023-05-26 01:11 UTC, xhaihao approved these changes
LGTM.

2023-05-26 01:17 UTC, xhaihao commented
> LGTM.

Seems large_scale_tile is not handled in cbs.

2023-05-26 02:13 UTC, xhaihao requested changes
need read / write large_scale_tile in cbs.

2023-11-27 06:19 UTC, xhaihao commented
@tengjinchung  May I close this PR ?

2023-11-27 06:22 UTC, tengjinchung commented
> @tengjinchung May I close this PR ?

sure.

2023-11-27 06:34 UTC, closed without merging